### ISSUE TITLE
AUC-ROC Curve as metric

### ISSUE THREAD

**Issue by wcheema-synsor** [Masmoudi-synsor/MOPS#4]
We are using the AUC-ROC (https://towardsdatascience.com/understanding-auc-roc-curve-68b2303cc9c5) curve as the metric for our production code so ideally we want CML to use AUC-ROC as the qualification metric. Try to add it as a metric to the workflow along with confusion matrix.

**Comment by Masmoudi-synsor** [comment]
done

**Comment by wcheema-synsor** [comment]
Could you please make a Pull request to merge this issue branch into your main branch. In case you already made the pull request just link the issue with it (on the right hand side in the pull request you will find the option to link the pull request with a specific issues) and add me as reviewer.
