### ISSUE TITLE
Control over trigger mechanisms

### ISSUE THREAD

**Issue by wcheema-synsor** [Masmoudi-synsor/MOPS#7]
It would be ideal to have higher control over when to trigger the Machine Learning tests since they can be expensive to run. Could you check if it is possible to do that and how it can be implemented.
E.g the Machine Learning tests do not run on every push of the code but only when a hyper-parameter is changed.

**Comment by Masmoudi-synsor** [comment]
I have restricted the trigger to only trigger when we make change to the ".py" files.

**Comment by wcheema-synsor** [comment]
Can it be extended to include only certain .py files ? For example only when changes are made to train.py but changes made to get_data.py does not trigger the actions.

**Comment by Masmoudi-synsor** [comment]
done.
